## データエンジニアリング

In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('../data/valve1.csv')

In [3]:
df.head(3)

,datetime,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
0,2020-03-09 10:14:33,0.026588,0.040111,1.33020,0.054711,79.3366,26.0199,233.062,32.0,0.0,0.0
1,2020-03-09 10:14:34,0.026170,0.040453,1.35399,0.382638,79.5158,26.0258,236.040,32.0,0.0,0.0
2,2020-03-09 10:14:35,0.026199,0.039419,1.54006,0.710565,79.3756,26.0265,251.380,32.0,0.0,0.0

In [4]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Accelerometer1RMS,18160.0,0.027338,0.000527,0.025553,0.026971,0.027346,0.027722,0.029031
Accelerometer2RMS,18160.0,0.040546,0.001168,0.037339,0.039761,0.040461,0.041192,0.053439
Current,18160.0,0.974279,0.273464,0.355411,0.739579,0.986835,1.202650,1.662610
Pressure,18160.0,0.063758,0.258584,-1.257000,0.054711,0.054711,0.054711,1.694350
Temperature,18160.0,70.207720,2.608980,65.188700,68.630525,69.765300,71.075925,79.889100
Thermocouple,18160.0,25.029108,0.447720,24.418700,24.674200,24.866800,25.423625,26.104400
Voltage,18160.0,230.710674,10.817408,203.135000,224.785750,230.959000,236.880500,255.324000
Volume Flow RateRMS,18160.0,31.284849,1.991965,22.000000,31.001000,32.000000,32.012600,33.969400
anomaly,18160.0,0.347412,0.476161,0.000000,0.000000,0.000000,1.000000,1.000000
changepoint,18160.0,0.003469,0.058799,0.000000,0.000000,0.000000,0.000000,1.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18160 entries, 0 to 18159
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   datetime             18160 non-null  object
 1   Accelerometer1RMS    18160 non-null  float64
 2   Accelerometer2RMS    18160 non-null  float64
 3   Current              18160 non-null  float64
 4   Pressure             18160 non-null  float64
 5   Temperature          18160 non-null  float64
 6   Thermocouple         18160 non-null  float64
 7   Voltage              18160 non-null  float64
 8   Volume Flow RateRMS  18160 non-null  float64
 9   anomaly              18160 non-null  float64
 10  changepoint          18160 non-null  float64
dtypes: float64(10), object(1)
memory usage: 1.5+ MB

In [6]:
print(df.groupby('anomaly').size())

anomaly
0.0    11851
1.0     6309
dtype: int64

In [7]:
df = df.drop(["datetime", "changepoint"], axis=1)
df.head(3)

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly
0,0.026588,0.040111,1.33020,0.054711,79.3366,26.0199,233.062,32.0,0.0
1,0.026170,0.040453,1.35399,0.382638,79.5158,26.0258,236.040,32.0,0.0
2,0.026199,0.039419,1.54006,0.710565,79.3756,26.0265,251.380,32.0,0.0

In [8]:
df_x = df.drop('anomaly', axis=1)
#目的変数
df_y = df.anomaly

In [9]:
(df_x_train, df_x_test, df_y_train, df_y_test) = train_test_split(df_x, df_y, test_size=0.3, random_state=0)

In [10]:
for name, item in {
    'df_x_train': df_x_train,
    'df_x_test': df_x_test,
    'df_y_train': df_y_train,
    'df_y_test': df_y_test
}.items():
    item.to_csv(f'../data/treated-data/{name}.csv', index=False)