## 1-1. データ収集

In [1]:
import pandas as pd
import os
import urllib.request

In [2]:
data_urls = {
    'valve1_1': 'https://raw.githubusercontent.com/waico/SKAB/master/data/valve1/1.csv',
    'valve1_2': 'https://raw.githubusercontent.com/waico/SKAB/master/data/valve1/2.csv',
    'valve1_3': 'https://raw.githubusercontent.com/waico/SKAB/master/data/valve1/3.csv',
    'valve1_4': 'https://raw.githubusercontent.com/waico/SKAB/master/data/valve1/4.csv',
}

dfs = []
for name, url in data_urls.items():
    file_path = f'../data/{name}.csv'
    if not os.path.exists(file_path):
        urllib.request.urlretrieve(url, file_path)
    df = pd.read_csv(file_path, sep=';')
    dfs.append(df)

# データの結合
df = pd.concat(dfs, ignore_index=True)
print(f"\n結合後のデータ: {len(df)} rows")
display(df.head(3))
display(df.describe().T)

df.to_csv('../data/valve1.csv', index=False)

結合後のデータ: 4463 rows

,datetime,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
0,2020-03-09 10:34:33,0.027080,0.039615,0.871339,0.054711,75.4955,25.8338,244.091,32.0000,0.0,0.0
1,2020-03-09 10:34:34,0.026995,0.038759,1.301280,0.054711,75.5445,25.8408,224.170,32.0000,0.0,0.0
2,2020-03-09 10:34:35,0.026807,0.039521,1.284500,0.382638,75.6607,25.8227,234.157,32.9986,0.0,0.0

,count,mean,std,min,25%,50%,75%,max
Accelerometer1RMS,4463.0,0.026954,0.000359,0.025584,0.026711,0.026957,0.027200,0.028162
Accelerometer2RMS,4463.0,0.040203,0.000917,0.037474,0.039561,0.040204,0.040814,0.053439
Current,4463.0,0.981591,0.276058,0.375488,0.748177,1.001980,1.210095,1.598950
Pressure,4463.0,0.073815,0.252949,-1.257000,0.054711,0.054711,0.054711,1.038490
Temperature,4463.0,71.717552,1.590074,67.973700,70.764700,71.326400,72.713600,76.280100
Thermocouple,4463.0,25.534661,0.154378,25.214600,25.435750,25.508000,25.655600,25.924000
Voltage,4463.0,230.760045,10.740647,203.725000,224.972000,231.006000,236.906500,254.957000
Volume Flow RateRMS,4463.0,31.684993,0.718542,29.005000,31.002000,32.000000,32.000000,33.000000
anomaly,4463.0,0.334304,0.471800,0.000000,0.000000,0.000000,1.000000,1.000000
changepoint,4463.0,0.003361,0.057883,0.000000,0.000000,0.000000,0.000000,1.000000