![tasks](../docs/tasks.png)

## 2-1. データ収集

本課題では、競馬のレースデータを用いて順位(1位, 3位以内, それ以外)を目的変数とし、馬の体重等のレースデータを説明変数とする問題を実施した。

In [2]:
import pandas as pd

from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('../data/unprocessed-data/race_data.csv')

In [4]:
df.head()

,Unnamed: 0,chakujun,wakuban,umaban,horse_name,horse_id,sex,age,kinryo,jockey_name,...,bataiju_sa,trainer_name,trainer_id,trainer_area,owner_name,owner_id,prize,race_id,time_seconds,rank_class
0,0,1.0,6,12,マイントラウム,2015104336,牝,3,54.0,石橋脩,...,-2.0,尾関知人,1103,東尾,社台レースホース,415800,500.0,201806020701,117.3,0.0
1,1,2.0,2,3,アポロレイア,2015101025,牝,3,54.0,勝浦正樹,...,2.0,鈴木伸尋,1026,東鈴,アポロサラブレッドクラブ,033700,200.0,201806020701,117.3,1.0
2,2,3.0,7,13,タオルデスカーフ,2015102084,牝,3,54.0,池添謙一,...,-4.0,大竹正博,1102,東大,山際辰夫,762033,130.0,201806020701,117.9,1.0
3,3,4.0,4,8,ジェイケイバスター,2015100844,牝,3,54.0,三浦皇成,...,-2.0,柴田政人,1007,東柴,小谷野次郎,702009,75.0,201806020701,118.1,2.0
4,4,5.0,1,1,アンシンカブル,2015101433,牝,3,54.0,柴田大知,...,-8.0,柴田政人,1007,東柴,水谷八重子,557005,50.0,201806020701,118.3,2.0

In [5]:
df = df.drop(columns=['Unnamed: 0'])
object_columns = df.select_dtypes(include='object').columns
df = df.drop(columns=object_columns)
df.columns

Index(['chakujun', 'wakuban', 'umaban', 'horse_id', 'age', 'kinryo',
       'jockey_id', 'agari', 'tansho', 'ninki', 'bataiju', 'bataiju_sa',
       'trainer_id', 'race_id', 'time_seconds', 'rank_class'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18661 entries, 0 to 18660
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   chakujun      18661 non-null  float64
 1   wakuban       18661 non-null  int64
 2   umaban        18661 non-null  int64
 3   horse_id      18661 non-null  int64
 4   age           18661 non-null  int64
 5   kinryo        18661 non-null  float64
 6   jockey_id     18661 non-null  int64
 7   agari         18661 non-null  float64
 8   tansho        18661 non-null  float64
 9   ninki         18661 non-null  float64
 10  bataiju       18661 non-null  float64
 11  bataiju_sa    18661 non-null  float64
 12  trainer_id    18661 non-null  int64
 13  race_id       18661 non-null  int64
 14  time_seconds  18661 non-null  float64
 15  rank_class    18661 non-null  float64
dtypes: float64(9), int64(7)
memory usage: 2.3 MB

In [7]:
df.head()

,chakujun,wakuban,umaban,horse_id,age,kinryo,jockey_id,agari,tansho,ninki,bataiju,bataiju_sa,trainer_id,race_id,time_seconds,rank_class
0,1.0,6,12,2015104336,3,54.0,1077,40.6,3.6,1.0,482.0,-2.0,1103,201806020701,117.3,0.0
1,2.0,2,3,2015101025,3,54.0,1025,41.1,5.3,4.0,456.0,2.0,1026,201806020701,117.3,1.0
2,3.0,7,13,2015102084,3,54.0,1032,40.6,35.9,8.0,478.0,-4.0,1102,201806020701,117.9,1.0
3,4.0,4,8,2015100844,3,54.0,1122,40.8,7.0,5.0,448.0,-2.0,1007,201806020701,118.1,2.0
4,5.0,1,1,2015101433,3,54.0,1009,40.7,184.7,13.0,414.0,-8.0,1007,201806020701,118.3,2.0

In [8]:
treated_df = df.drop(columns=["chakujun","horse_id", "jockey_id", "trainer_id"])

In [9]:
treated_df.head()

,wakuban,umaban,age,kinryo,agari,tansho,ninki,bataiju,bataiju_sa,race_id,time_seconds,rank_class
0,6,12,3,54.0,40.6,3.6,1.0,482.0,-2.0,201806020701,117.3,0.0
1,2,3,3,54.0,41.1,5.3,4.0,456.0,2.0,201806020701,117.3,1.0
2,7,13,3,54.0,40.6,35.9,8.0,478.0,-4.0,201806020701,117.9,1.0
3,4,8,3,54.0,40.8,7.0,5.0,448.0,-2.0,201806020701,118.1,2.0
4,1,1,3,54.0,40.7,184.7,13.0,414.0,-8.0,201806020701,118.3,2.0

In [10]:
treated_df.describe().T

,count,mean,std,min,25%,50%,75%,max
wakuban,18661.0,4.766518e+00,2.271706e+00,1.000000e+00,3.000000e+00,5.000000e+00,7.000000e+00,8.000000e+00
umaban,18661.0,7.792455e+00,4.434985e+00,1.000000e+00,4.000000e+00,8.000000e+00,1.100000e+01,1.800000e+01
age,18661.0,3.631745e+00,1.344700e+00,2.000000e+00,3.000000e+00,3.000000e+00,4.000000e+00,1.200000e+01
kinryo,18661.0,5.516317e+01,1.876922e+00,4.800000e+01,5.400000e+01,5.500000e+01,5.600000e+01,6.300000e+01
agari,18661.0,3.640558e+01,4.680278e+00,1.290000e+01,3.530000e+01,3.680000e+01,3.850000e+01,7.160000e+01
tansho,18661.0,6.884084e+01,1.020497e+02,1.100000e+00,8.100000e+00,2.490000e+01,8.290000e+01,8.542000e+02
ninki,18661.0,7.759070e+00,4.420082e+00,1.000000e+00,4.000000e+00,7.000000e+00,1.100000e+01,1.800000e+01
bataiju,18661.0,4.707642e+02,3.032595e+01,3.300000e+02,4.500000e+02,4.700000e+02,4.920000e+02,6.060000e+02
bataiju_sa,18661.0,3.768823e-01,6.228682e+00,-3.900000e+01,-3.000000e+00,0.000000e+00,4.000000e+00,6.600000e+01
race_id,18661.0,2.021418e+11,2.282114e+08,2.018010e+11,2.019090e+11,2.021071e+11,2.023091e+11,2.025100e+11
time_seconds,18661.0,1.018861e+02,2.964180e+01,5.420000e+01,8.000000e+01,9.850000e+01,1.167000e+02,2.899000e+02
rank_class,18661.0,1.712502e+00,5.906821e-01,0.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00

In [11]:
df_x = treated_df.drop('rank_class', axis=1)
#目的変数
df_y = treated_df.rank_class

In [12]:
df_x_train, df_x_test, df_y_train, df_y_test = train_test_split(df_x, df_y, test_size=0.3, random_state=42, stratify=df_y)

In [13]:
for name, item in {
    'df_x_train': df_x_train,
    'df_x_test': df_x_test,
    'df_y_train': df_y_train,
    'df_y_test': df_y_test
}.items():
    item.to_csv(f'../data/treated-data/task2/{name}.csv', index=False)